/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CtrlEvent;
import controller.CtrlPlace;
import controller.CtrlReservation;
import controller.CtrlTripAdvisor;
import controller.CtrlUser;
import java.awt.Color;
import model.RolDAO;
import model.User;

/**
 *
 * @author Diego
 */
public class frmAdmin extends javax.swing.JFrame {
    
    CtrlTripAdvisor cta = new CtrlTripAdvisor();
    CtrlEvent ce = new CtrlEvent();
    CtrlReservation cr = new CtrlReservation();
    CtrlUser cu = new CtrlUser();
    CtrlPlace cp = new CtrlPlace();
    RolDAO rol = new RolDAO();

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setUserInfo(user);
        loadUsers();
        loadEvent();
        loadReservation();
        loadPlace();
    }
    
    private void loadUsers() {
        cu.loadDataUser(tblUsers);
    }

    private void loadEvent() {
        ce.loadDataEvent(tblEvents);
    }
    
    private void loadReservation() {
        cr.loadDataReservation(tblReservations);
    }
    
    private void loadPlace() {
        cp.loadDataPlace(tblPlaces);
    }
    
    public void setUserInfo(User user) {
        txtIdNumberProfile.setText(String.valueOf(user.getID_number()));
        txtNameProfile.setText(user.getName());
        txtLastNameProfile.setText(user.getLast_name());
        txtEmailProfile.setText(user.getEmail());
        txtBirthDateProfile.setText(String.valueOf(user.getBirth_date()));
        txtPasswordProfile.setText(user.getPassword());
        txtPhoneProfile.setText(String.valueOf(user.getPhone_number()));
    }
    
    private void clearFields() {
        cu.clearFields(txtIdNumberUser, txtNameUser, txtLastNameUser, txtBirthDateUser, txtEmailUser, txtPhoneUser, txtPasswordUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        btnPanel3 = new javax.swing.JButton();
        btnPanel5 = new javax.swing.JButton();
        jpMenu = new javax.swing.JPanel();
        btnPanel1 = new javax.swing.JButton();
        btnPanel2 = new javax.swing.JButton();
        btnPanel4 = new javax.swing.JButton();
        btnPanel6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tabPanels = new javax.swing.JTabbedPane();
        jpSearch = new javax.swing.JPanel();
        lblHeader1 = new javax.swing.JLabel();
        btnClearFilter = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        btnDeleteEvent = new javax.swing.JButton();
        jpReservations = new javax.swing.JPanel();
        lblHeaderReservations = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        btnDeleteReserv = new javax.swing.JButton();
        jpmyProfile = new javax.swing.JPanel();
        lblLastName = new javax.swing.JLabel();
        txtLastNameProfile = new javax.swing.JTextField();
        txtEmailProfile = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblNameUser = new javax.swing.JLabel();
        lblHeaderMyProfile = new javax.swing.JLabel();
        txtIdNumberProfile = new javax.swing.JTextField();
        txtNameProfile = new javax.swing.JTextField();
        lblId_number = new javax.swing.JLabel();
        btnUpdateInfoAdmin = new javax.swing.JButton();
        lblEmailUser = new javax.swing.JLabel();
        txtPasswordProfile = new javax.swing.JPasswordField();
        lblBirthDate = new javax.swing.JLabel();
        btnBirthCalendar = new javax.swing.JButton();
        txtBirthDateProfile = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhoneProfile = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jpUserSettings = new javax.swing.JPanel();
        lblLastName1 = new javax.swing.JLabel();
        txtLastNameUser = new javax.swing.JTextField();
        txtEmailUser = new javax.swing.JTextField();
        lblPassword1 = new javax.swing.JLabel();
        lblNameUser1 = new javax.swing.JLabel();
        lblHeaderMyProfile1 = new javax.swing.JLabel();
        txtIdNumberUser = new javax.swing.JTextField();
        txtNameUser = new javax.swing.JTextField();
        lblId_number1 = new javax.swing.JLabel();
        btnUpdateInfoUser = new javax.swing.JButton();
        lblEmailUser1 = new javax.swing.JLabel();
        txtPasswordUser = new javax.swing.JPasswordField();
        lblBirthDate1 = new javax.swing.JLabel();
        btnBirthCalendar1 = new javax.swing.JButton();
        txtBirthDateUser = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtPhoneUser = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnDeleteUser = new javax.swing.JButton();
        jpPlace = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPlaces = new javax.swing.JTable();
        btnDeletePlace = new javax.swing.JButton();
        lblHeaderMyProfile2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Eventos - Modo Administrador - v1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBack.setBackground(new java.awt.Color(0, 0, 69));

        btnPanel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPanel3.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/usuario.png"))); // NOI18N
        btnPanel3.setText("Mi Perfil");
        btnPanel3.setBorderPainted(false);
        btnPanel3.setContentAreaFilled(false);
        btnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel3ActionPerformed(evt);
            }
        });

        btnPanel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPanel5.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/usuario.png"))); // NOI18N
        btnPanel5.setText("Salir");
        btnPanel5.setBorderPainted(false);
        btnPanel5.setContentAreaFilled(false);
        btnPanel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBackLayout = new javax.swing.GroupLayout(jpBack);
        jpBack.setLayout(jpBackLayout);
        jpBackLayout.setHorizontalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackLayout.createSequentialGroup()
                .addGap(789, 789, 789)
                .addComponent(btnPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jpBackLayout.setVerticalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jpBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1080, 70));

        jpMenu.setBackground(new java.awt.Color(224, 35, 52));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnPanel1.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/plano-alt.png"))); // NOI18N
        btnPanel1.setText("Eventos");
        btnPanel1.setBorderPainted(false);
        btnPanel1.setContentAreaFilled(false);
        btnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel1ActionPerformed(evt);
            }
        });
        jpMenu.add(btnPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 198, 37));

        btnPanel2.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnPanel2.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/billete-de-avion.png"))); // NOI18N
        btnPanel2.setText("Ver reservaciones");
        btnPanel2.setBorderPainted(false);
        btnPanel2.setContentAreaFilled(false);
        btnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel2ActionPerformed(evt);
            }
        });
        jpMenu.add(btnPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 198, 41));

        btnPanel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnPanel4.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/usuario.png"))); // NOI18N
        btnPanel4.setText("Usuarios");
        btnPanel4.setBorderPainted(false);
        btnPanel4.setContentAreaFilled(false);
        btnPanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel4ActionPerformed(evt);
            }
        });
        jpMenu.add(btnPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, 198, 41));

        btnPanel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnPanel6.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/plano-alt.png"))); // NOI18N
        btnPanel6.setText("Lugares");
        btnPanel6.setBorderPainted(false);
        btnPanel6.setContentAreaFilled(false);
        btnPanel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel6ActionPerformed(evt);
            }
        });
        jpMenu.add(btnPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 198, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/bosque_tropical_1270_x_720.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jpMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 850));

        lblHeader1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblHeader1.setText("Eventos");

        btnClearFilter.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnClearFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/escoba.png"))); // NOI18N
        btnClearFilter.setText("Limpiar mi búsqueda anterior");
        btnClearFilter.setContentAreaFilled(false);

        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Fecha", "Direccion", "Ciudad", "Codigo postal", "Place"
            }
        ));
        tblEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblEvents);

        btnDeleteEvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/borrar-usuario.png"))); // NOI18N
        btnDeleteEvent.setText("Eliminar");
        btnDeleteEvent.setBorderPainted(false);
        btnDeleteEvent.setContentAreaFilled(false);
        btnDeleteEvent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteEvent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSearchLayout = new javax.swing.GroupLayout(jpSearch);
        jpSearch.setLayout(jpSearchLayout);
        jpSearchLayout.setHorizontalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addGroup(jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSearchLayout.createSequentialGroup()
                        .addGap(694, 694, 694)
                        .addComponent(btnClearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSearchLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpSearchLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jpSearchLayout.setVerticalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeader1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSearchLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327)
                        .addComponent(btnClearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeleteEvent))
                .addGap(18, 18, 18))
        );

        tabPanels.addTab("Eventos Disponibles", jpSearch);

        lblHeaderReservations.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblHeaderReservations.setText("Reservaciones");

        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre Usuario", "Fecha", "Entradas", "Evento"
            }
        ));
        tblReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReservations);

        btnDeleteReserv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteReserv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/borrar-usuario.png"))); // NOI18N
        btnDeleteReserv.setText("Eliminar");
        btnDeleteReserv.setBorderPainted(false);
        btnDeleteReserv.setContentAreaFilled(false);
        btnDeleteReserv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteReserv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReservActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpReservationsLayout = new javax.swing.GroupLayout(jpReservations);
        jpReservations.setLayout(jpReservationsLayout);
        jpReservationsLayout.setHorizontalGroup(
            jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservationsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeaderReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpReservationsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnDeleteReserv, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jpReservationsLayout.setVerticalGroup(
            jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservationsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeaderReservations)
                .addGap(18, 18, 18)
                .addGroup(jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteReserv))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tabPanels.addTab("Reservaciones", jpReservations);

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName.setText("Apellidos:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Contraseña:");

        lblNameUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameUser.setText("Cedula");

        lblHeaderMyProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeaderMyProfile.setText("Editar Mi Perfil");
        lblHeaderMyProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeaderMyProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        txtIdNumberProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNumberProfileActionPerformed(evt);
            }
        });

        lblId_number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId_number.setText("Nombre");

        btnUpdateInfoAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateInfoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/cargando.png"))); // NOI18N
        btnUpdateInfoAdmin.setText("Actualizar");
        btnUpdateInfoAdmin.setBorderPainted(false);
        btnUpdateInfoAdmin.setContentAreaFilled(false);
        btnUpdateInfoAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateInfoAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateInfoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInfoAdminActionPerformed(evt);
            }
        });

        lblEmailUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailUser.setText("Correo:");

        lblBirthDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBirthDate.setText("Fecha de Nacimiento:");

        btnBirthCalendar.setText("...");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone.setText("Número de Teléfono:");

        javax.swing.GroupLayout jpmyProfileLayout = new javax.swing.GroupLayout(jpmyProfile);
        jpmyProfile.setLayout(jpmyProfileLayout);
        jpmyProfileLayout.setHorizontalGroup(
            jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmyProfileLayout.createSequentialGroup()
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpmyProfileLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword)
                            .addComponent(lblEmailUser)
                            .addComponent(lblId_number)
                            .addComponent(lblLastName)
                            .addComponent(lblNameUser)
                            .addComponent(lblBirthDate)
                            .addComponent(lblPhone))
                        .addGap(32, 32, 32)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameProfile)
                            .addComponent(txtIdNumberProfile)
                            .addComponent(txtLastNameProfile)
                            .addComponent(txtEmailProfile)
                            .addComponent(txtPasswordProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtBirthDateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtPhoneProfile))
                        .addGap(18, 18, 18)
                        .addComponent(btnBirthCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpmyProfileLayout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(btnUpdateInfoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpmyProfileLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeaderMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jpmyProfileLayout.setVerticalGroup(
            jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmyProfileLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHeaderMyProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameUser)
                    .addComponent(txtIdNumberProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId_number)
                    .addComponent(txtNameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastNameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailUser)
                    .addComponent(txtEmailProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirthDateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthDate)
                    .addComponent(btnBirthCalendar))
                .addGap(12, 12, 12)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPasswordProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhoneProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnUpdateInfoAdmin)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        tabPanels.addTab("Mi Perfil", jpmyProfile);

        lblLastName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName1.setText("Apellidos:");

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword1.setText("Contraseña:");

        lblNameUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameUser1.setText("Cedula");

        lblHeaderMyProfile1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeaderMyProfile1.setText("Editar Usuarios:");
        lblHeaderMyProfile1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeaderMyProfile1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblId_number1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId_number1.setText("Nombre");

        btnUpdateInfoUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateInfoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/actUsuario.png"))); // NOI18N
        btnUpdateInfoUser.setText("Actualizar");
        btnUpdateInfoUser.setBorderPainted(false);
        btnUpdateInfoUser.setContentAreaFilled(false);
        btnUpdateInfoUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateInfoUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInfoUserActionPerformed(evt);
            }
        });

        lblEmailUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailUser1.setText("Correo:");

        lblBirthDate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBirthDate1.setText("Fecha de Nacimiento:");

        btnBirthCalendar1.setText("...");

        lblPhone1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone1.setText("Número de Teléfono:");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cedula", "Nombre", "Apellidos", "Fecha Nacimiento", "Correo", "Telefono", "Contraseña", "Rol"
            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsers);

        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/borrar-usuario.png"))); // NOI18N
        btnDeleteUser.setText("Eliminar usuario");
        btnDeleteUser.setBorderPainted(false);
        btnDeleteUser.setContentAreaFilled(false);
        btnDeleteUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUserSettingsLayout = new javax.swing.GroupLayout(jpUserSettings);
        jpUserSettings.setLayout(jpUserSettingsLayout);
        jpUserSettingsLayout.setHorizontalGroup(
            jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserSettingsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUserSettingsLayout.createSequentialGroup()
                        .addComponent(lblHeaderMyProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpUserSettingsLayout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addGap(39, 39, 39))
                    .addGroup(jpUserSettingsLayout.createSequentialGroup()
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblId_number1)
                            .addComponent(lblLastName1)
                            .addComponent(lblNameUser1)
                            .addComponent(lblBirthDate1)
                            .addGroup(jpUserSettingsLayout.createSequentialGroup()
                                .addComponent(btnUpdateInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addComponent(lblEmailUser1)
                            .addComponent(lblPhone1)
                            .addComponent(lblPassword1))
                        .addGap(32, 32, 32)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpUserSettingsLayout.createSequentialGroup()
                                    .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNameUser)
                                        .addComponent(txtIdNumberUser)
                                        .addComponent(txtLastNameUser)
                                        .addComponent(txtBirthDateUser)
                                        .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBirthCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jpUserSettingsLayout.setVerticalGroup(
            jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserSettingsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHeaderMyProfile1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUserSettingsLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameUser1)
                            .addComponent(txtIdNumberUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId_number1)
                            .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBirthDate1)
                            .addComponent(txtBirthDateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBirthCalendar1))
                        .addGap(9, 9, 9)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailUser1)
                            .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone1))
                        .addGap(12, 12, 12)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword1))
                        .addGap(70, 70, 70)
                        .addGroup(jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdateInfoUser)
                            .addComponent(btnDeleteUser)))
                    .addGroup(jpUserSettingsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        tabPanels.addTab("Gestión de usuarios", jpUserSettings);

        tblPlaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Direccion", "Ciudad", "Codigo Postal", "Latitud", "Longitud", "WebLink"
            }
        ));
        tblPlaces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlacesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPlaces);

        btnDeletePlace.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeletePlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/borrar-usuario.png"))); // NOI18N
        btnDeletePlace.setText("Eliminar");
        btnDeletePlace.setBorderPainted(false);
        btnDeletePlace.setContentAreaFilled(false);
        btnDeletePlace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletePlace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletePlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePlaceActionPerformed(evt);
            }
        });

        lblHeaderMyProfile2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeaderMyProfile2.setText("Lugares");
        lblHeaderMyProfile2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeaderMyProfile2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jpPlaceLayout = new javax.swing.GroupLayout(jpPlace);
        jpPlace.setLayout(jpPlaceLayout);
        jpPlaceLayout.setHorizontalGroup(
            jpPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlaceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPlaceLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHeaderMyProfile2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jpPlaceLayout.setVerticalGroup(
            jpPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlaceLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHeaderMyProfile2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePlace))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        tabPanels.addTab("Lugares", jpPlace);

        getContentPane().add(tabPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1080, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel1ActionPerformed
        tabPanels.setSelectedIndex(0);
    }//GEN-LAST:event_btnPanel1ActionPerformed

    private void btnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel2ActionPerformed
        tabPanels.setSelectedIndex(1);
    }//GEN-LAST:event_btnPanel2ActionPerformed

    private void btnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel3ActionPerformed
        tabPanels.setSelectedIndex(2);
    }//GEN-LAST:event_btnPanel3ActionPerformed

    private void btnPanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel4ActionPerformed
        tabPanels.setSelectedIndex(3);
    }//GEN-LAST:event_btnPanel4ActionPerformed

    private void btnPanel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel5ActionPerformed
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPanel5ActionPerformed

    private void btnUpdateInfoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInfoAdminActionPerformed
        cu.setRolId(1);
        cu.updatedUser(txtIdNumberProfile, txtNameProfile, txtLastNameProfile, txtBirthDateProfile, txtEmailProfile, txtPhoneProfile, txtPasswordProfile);
        loadUsers();
    }//GEN-LAST:event_btnUpdateInfoAdminActionPerformed

    private void btnUpdateInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInfoUserActionPerformed
        int selectedRow = tblUsers.getSelectedRow();
        Object rolName = tblUsers.getValueAt(selectedRow, 8);
        cu.setRolId(rol.getIDRol((String) rolName));
        cu.updatedUser(txtIdNumberUser, txtNameUser, txtLastNameUser, txtBirthDateUser, txtEmailUser, txtPhoneUser, txtPasswordUser);
        loadUsers();
        clearFields();
    }//GEN-LAST:event_btnUpdateInfoUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        cu.deleteuser();
        loadUsers();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void txtIdNumberProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNumberProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdNumberProfileActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        cu.selectedRow(tblUsers, txtIdNumberUser, txtNameUser, txtLastNameUser, txtBirthDateUser, txtEmailUser, txtPhoneUser, txtPasswordUser);
    }//GEN-LAST:event_tblUsersMouseClicked

    private void btnPanel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel6ActionPerformed
        tabPanels.setSelectedIndex(4);
    }//GEN-LAST:event_btnPanel6ActionPerformed

    private void btnDeleteReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReservActionPerformed
        cr.deleteReserv();
        loadReservation();
    }//GEN-LAST:event_btnDeleteReservActionPerformed

    private void btnDeleteEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEventActionPerformed
        ce.deleteEvent();
        loadEvent();
    }//GEN-LAST:event_btnDeleteEventActionPerformed

    private void btnDeletePlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePlaceActionPerformed
        cp.deletePlace();
        loadPlace();
    }//GEN-LAST:event_btnDeletePlaceActionPerformed

    private void tblReservationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservationsMouseClicked
        cr.selectedRow(tblReservations);
    }//GEN-LAST:event_tblReservationsMouseClicked

    private void tblEventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventsMouseClicked
        ce.selectedRow(tblEvents);
    }//GEN-LAST:event_tblEventsMouseClicked

    private void tblPlacesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlacesMouseClicked
        cp.selectedRow(tblPlaces);
    }//GEN-LAST:event_tblPlacesMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBirthCalendar;
    private javax.swing.JButton btnBirthCalendar1;
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton btnDeleteEvent;
    private javax.swing.JButton btnDeletePlace;
    private javax.swing.JButton btnDeleteReserv;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnPanel1;
    private javax.swing.JButton btnPanel2;
    private javax.swing.JButton btnPanel3;
    private javax.swing.JButton btnPanel4;
    private javax.swing.JButton btnPanel5;
    private javax.swing.JButton btnPanel6;
    private javax.swing.JButton btnUpdateInfoAdmin;
    private javax.swing.JButton btnUpdateInfoUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel jpBack;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPlace;
    private javax.swing.JPanel jpReservations;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JPanel jpUserSettings;
    private javax.swing.JPanel jpmyProfile;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblBirthDate1;
    private javax.swing.JLabel lblEmailUser;
    private javax.swing.JLabel lblEmailUser1;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeaderMyProfile;
    private javax.swing.JLabel lblHeaderMyProfile1;
    private javax.swing.JLabel lblHeaderMyProfile2;
    private javax.swing.JLabel lblHeaderReservations;
    private javax.swing.JLabel lblId_number;
    private javax.swing.JLabel lblId_number1;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblNameUser1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JTabbedPane tabPanels;
    private javax.swing.JTable tblEvents;
    private javax.swing.JTable tblPlaces;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtBirthDateProfile;
    private javax.swing.JTextField txtBirthDateUser;
    private javax.swing.JTextField txtEmailProfile;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtIdNumberProfile;
    private javax.swing.JTextField txtIdNumberUser;
    private javax.swing.JTextField txtLastNameProfile;
    private javax.swing.JTextField txtLastNameUser;
    private javax.swing.JTextField txtNameProfile;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JPasswordField txtPasswordProfile;
    private javax.swing.JPasswordField txtPasswordUser;
    private javax.swing.JTextField txtPhoneProfile;
    private javax.swing.JTextField txtPhoneUser;
    // End of variables declaration//GEN-END:variables
}
