/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Diego
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        btnPanel1 = new javax.swing.JButton();
        btnPanel2 = new javax.swing.JButton();
        btnPanel3 = new javax.swing.JButton();
        btnPanel4 = new javax.swing.JButton();
        tabPanels = new javax.swing.JTabbedPane();
        jpSearch = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        jpReservations = new javax.swing.JPanel();
        lblHeaderReservations = new javax.swing.JLabel();
        jpmyProfile = new javax.swing.JPanel();
        lblMyProfileHeader = new javax.swing.JLabel();
        jpUserSettings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Eventos - Modo Administrador - v1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBack.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout jpBackLayout = new javax.swing.GroupLayout(jpBack);
        jpBack.setLayout(jpBackLayout);
        jpBackLayout.setHorizontalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        jpBackLayout.setVerticalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jpBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1170, 70));

        jpMenu.setBackground(new java.awt.Color(153, 102, 0));

        btnPanel1.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel1.setText("Buscar eventos");
        btnPanel1.setBorderPainted(false);
        btnPanel1.setContentAreaFilled(false);
        btnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel1ActionPerformed(evt);
            }
        });

        btnPanel2.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel2.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel2.setText("Ver reservaciones");
        btnPanel2.setBorderPainted(false);
        btnPanel2.setContentAreaFilled(false);
        btnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel2ActionPerformed(evt);
            }
        });

        btnPanel3.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel3.setText("Mi Perfil");
        btnPanel3.setBorderPainted(false);
        btnPanel3.setContentAreaFilled(false);
        btnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel3ActionPerformed(evt);
            }
        });

        btnPanel4.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel4.setText("Usuarios");
        btnPanel4.setBorderPainted(false);
        btnPanel4.setContentAreaFilled(false);
        btnPanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btnPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(496, Short.MAX_VALUE))
        );

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 850));

        lblHeader.setText("Buscar eventos cerca de mi");

        javax.swing.GroupLayout jpSearchLayout = new javax.swing.GroupLayout(jpSearch);
        jpSearch.setLayout(jpSearchLayout);
        jpSearchLayout.setHorizontalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(lblHeader)
                .addContainerGap(510, Short.MAX_VALUE))
        );
        jpSearchLayout.setVerticalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeader)
                .addContainerGap(724, Short.MAX_VALUE))
        );

        tabPanels.addTab("Eventos Disponibles", jpSearch);

        lblHeaderReservations.setText("Ver reservaciones");

        javax.swing.GroupLayout jpReservationsLayout = new javax.swing.GroupLayout(jpReservations);
        jpReservations.setLayout(jpReservationsLayout);
        jpReservationsLayout.setHorizontalGroup(
            jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservationsLayout.createSequentialGroup()
                .addGap(476, 476, 476)
                .addComponent(lblHeaderReservations)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        jpReservationsLayout.setVerticalGroup(
            jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservationsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblHeaderReservations)
                .addContainerGap(706, Short.MAX_VALUE))
        );

        tabPanels.addTab("Reservaciones", jpReservations);

        lblMyProfileHeader.setText("Mi perfil personal");

        javax.swing.GroupLayout jpmyProfileLayout = new javax.swing.GroupLayout(jpmyProfile);
        jpmyProfile.setLayout(jpmyProfileLayout);
        jpmyProfileLayout.setHorizontalGroup(
            jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmyProfileLayout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(lblMyProfileHeader)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        jpmyProfileLayout.setVerticalGroup(
            jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmyProfileLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblMyProfileHeader)
                .addContainerGap(710, Short.MAX_VALUE))
        );

        tabPanels.addTab("Mi Perfil", jpmyProfile);

        jLabel1.setText("Gestor de usuarios en el sistema");

        javax.swing.GroupLayout jpUserSettingsLayout = new javax.swing.GroupLayout(jpUserSettings);
        jpUserSettings.setLayout(jpUserSettingsLayout);
        jpUserSettingsLayout.setHorizontalGroup(
            jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserSettingsLayout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addComponent(jLabel1)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jpUserSettingsLayout.setVerticalGroup(
            jpUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserSettingsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(706, Short.MAX_VALUE))
        );

        tabPanels.addTab("Gestión de usuarios", jpUserSettings);

        getContentPane().add(tabPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 1130, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel1ActionPerformed
         tabPanels.setSelectedIndex(0);
    }//GEN-LAST:event_btnPanel1ActionPerformed

    private void btnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel2ActionPerformed
        tabPanels.setSelectedIndex(1);
    }//GEN-LAST:event_btnPanel2ActionPerformed

    private void btnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel3ActionPerformed
        tabPanels.setSelectedIndex(2);
    }//GEN-LAST:event_btnPanel3ActionPerformed

    private void btnPanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel4ActionPerformed
       tabPanels.setSelectedIndex(3);
    }//GEN-LAST:event_btnPanel4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanel1;
    private javax.swing.JButton btnPanel2;
    private javax.swing.JButton btnPanel3;
    private javax.swing.JButton btnPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpBack;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpReservations;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JPanel jpUserSettings;
    private javax.swing.JPanel jpmyProfile;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeaderReservations;
    private javax.swing.JLabel lblMyProfileHeader;
    private javax.swing.JTabbedPane tabPanels;
    // End of variables declaration//GEN-END:variables
}
