/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CtrlUser;

/**
 *
 * @author Diego
 */
public class frmRegister extends javax.swing.JFrame {

    CtrlUser cu = new CtrlUser();

    /**
     * Creates new form frmRegister
     */
    public frmRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPanel5 = new javax.swing.JButton();
        lblHeaderMyProfile = new javax.swing.JLabel();
        txtNameUser = new javax.swing.JTextField();
        lblNameUser = new javax.swing.JLabel();
        lblId_number = new javax.swing.JLabel();
        txtIdNumberUser = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblEmailUser = new javax.swing.JLabel();
        txtEmailUser = new javax.swing.JTextField();
        lblBirthDate = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnUpdateInfoUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar nuevo usuario - Sistema de Eventos 1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPanel5.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/actUsuario.png"))); // NOI18N
        btnPanel5.setText("Volver atrás");
        btnPanel5.setContentAreaFilled(false);
        btnPanel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 26, 136, -1));

        lblHeaderMyProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeaderMyProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderMyProfile.setText("Registro de nuevo usuario");
        lblHeaderMyProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeaderMyProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblHeaderMyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 64, 246, -1));
        getContentPane().add(txtNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 144, 207, -1));

        lblNameUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNameUser.setText("Nombre:");
        getContentPane().add(lblNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 145, -1, -1));

        lblId_number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId_number.setForeground(new java.awt.Color(255, 255, 255));
        lblId_number.setText("Cédula:");
        getContentPane().add(lblId_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 181, -1, -1));
        getContentPane().add(txtIdNumberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 180, 207, -1));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Apellidos:");
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 217, -1, -1));
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 216, 207, -1));

        lblEmailUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailUser.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailUser.setText("Correo:");
        getContentPane().add(lblEmailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 253, -1, -1));
        getContentPane().add(txtEmailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 252, 207, -1));

        lblBirthDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthDate.setText("Fecha de Nacimiento:");
        getContentPane().add(lblBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 289, -1, -1));
        getContentPane().add(txtBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 288, 207, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña*:");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 324, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 324, 207, -1));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Número de Teléfono:");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 358, -1, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 357, 207, -1));

        btnUpdateInfoUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateInfoUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateInfoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/caja.png"))); // NOI18N
        btnUpdateInfoUser.setText("Registrarme");
        btnUpdateInfoUser.setBorderPainted(false);
        btnUpdateInfoUser.setContentAreaFilled(false);
        btnUpdateInfoUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateInfoUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInfoUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateInfoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 434, 111, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("* La contraseña debe de ser de al menos 8 caracteres, incluir mayúsculas y minúsculas, así como un número.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 524, 686, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/bosque_tropical_1270_x_720 (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInfoUserActionPerformed
        cu.setRolId(2);
        cu.addUserRegister(txtIdNumberUser, txtNameUser, txtLastName, txtBirthDate, txtEmailUser, txtPhone, txtPassword, this);
    }//GEN-LAST:event_btnUpdateInfoUserActionPerformed

    private void btnPanel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel5ActionPerformed
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPanel5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanel5;
    private javax.swing.JButton btnUpdateInfoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblEmailUser;
    private javax.swing.JLabel lblHeaderMyProfile;
    private javax.swing.JLabel lblId_number;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtIdNumberUser;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
