/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CtrlReservation;
import controller.CtrlTripAdvisor;
import controller.CtrlUser;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Event;
import model.EventDAO;
import model.Place;
import model.PlaceDAO;
import model.User;

/**
 *
 * @author Bravo
 */
public class frmUser extends javax.swing.JFrame {

    CtrlTripAdvisor cta = new CtrlTripAdvisor();
    CtrlUser cu = new CtrlUser();
    CtrlReservation cr = new CtrlReservation();
    EventDAO eventDAO = new EventDAO();
    PlaceDAO placeDAO = new PlaceDAO();
    private EventPanel eventPanel;
    private User user;

    /**
     * Creates new form frmUser
     */
    public frmUser(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setUserInfo(user);
        this.user = user;
        loadReservation();
    }

    public void setEventPanel(EventPanel eventPanel) {
        this.eventPanel = eventPanel;
    }

    public void setUserInfo(User user) {
        cu.setId(user.getId());
        txtNameProfile.setText(user.getName());
        txtIdNumberProfile.setText(String.valueOf(user.getID_number()));
        txtLastNameProfile.setText(user.getLast_name());
        txtEmailProfile.setText(user.getEmail());
        Date birthDate = user.getBirth_date();
        if (birthDate != null) {
            jdcUser.setDate(birthDate);
        } else {
            jdcUser.setDate(null);
        }
        txtPasswordProfile.setText(user.getPassword());
        txtPhoneProfile.setText(String.valueOf(user.getPhone_number()));
    }

    public void actualizarFecha(String name) {
        // Get the current date and time
        LocalDateTime fechaActual = LocalDateTime.now();

        // Format the date as a string in the desired format
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String fechaFormateada = fechaActual.format(formato);
        txtDateR.setText(fechaFormateada);
        txtEventId.setText(name);
        txtUserR.setText(user.getName());
    }

    public void getJpReservations() {
        tabPanels.setSelectedIndex(1);
    }

    public void setEventDetails(Event event) {
        try {
            eventDAO.create(event);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al insertar el evento en la base de datos: " + e.toString());
        }
    }

    public void setPlaceDetails(Place place) {
        try {
            placeDAO.create(place);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al insertar el lugar en la base de datos: " + e.toString());
        }
    }

    private void loadReservation() {
        cr.loadDataReservationByName(tblReservations, user.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        btnPanel3 = new javax.swing.JButton();
        btnPanel4 = new javax.swing.JButton();
        tabPanels = new javax.swing.JTabbedPane();
        jpSearch = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        jPFilters = new javax.swing.JPanel();
        lblFilterByName = new javax.swing.JLabel();
        txtFilterByName = new javax.swing.JTextField();
        lblBeginDate = new javax.swing.JLabel();
        lblFinalDate = new javax.swing.JLabel();
        lblFilterByLocation = new javax.swing.JLabel();
        txtFilterByLocation = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnFilter = new javax.swing.JButton();
        boxCategory = new javax.swing.JComboBox<>();
        jdcStar = new com.toedter.calendar.JDateChooser();
        jdcFinish = new com.toedter.calendar.JDateChooser();
        scrollAvailable = new javax.swing.JScrollPane();
        btnClearFilter = new javax.swing.JButton();
        jpReservations = new javax.swing.JPanel();
        lblHeaderReservations = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUserR = new javax.swing.JLabel();
        txtUserR = new javax.swing.JTextField();
        lblDateR = new javax.swing.JLabel();
        txtDateR = new javax.swing.JTextField();
        lblQuantityR = new javax.swing.JLabel();
        spQuantityR = new javax.swing.JSpinner();
        lblEventId = new javax.swing.JLabel();
        txtEventId = new javax.swing.JTextField();
        btnConfirmR = new javax.swing.JButton();
        btnDisconfirmR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        lblHeaderReservations1 = new javax.swing.JLabel();
        jpmyProfile = new javax.swing.JPanel();
        lblLastName = new javax.swing.JLabel();
        txtLastNameProfile = new javax.swing.JTextField();
        txtEmailProfile = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblNameUser = new javax.swing.JLabel();
        lblHeaderMyProfile = new javax.swing.JLabel();
        txtNameProfile = new javax.swing.JTextField();
        lblId_number = new javax.swing.JLabel();
        txtIdNumberProfile = new javax.swing.JTextField();
        btnUpdateInfoUser = new javax.swing.JButton();
        lblEmailUser = new javax.swing.JLabel();
        txtPasswordProfile = new javax.swing.JPasswordField();
        lblBirthDate = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtPhoneProfile = new javax.swing.JTextField();
        jdcUser = new com.toedter.calendar.JDateChooser();
        jpMenu = new javax.swing.JPanel();
        btnPanel1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel para Usuario - Sistema de Eventos 1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBack.setBackground(new java.awt.Color(0, 0, 0));

        btnPanel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPanel3.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/usuario.png"))); // NOI18N
        btnPanel3.setText("Mi Perfil");
        btnPanel3.setBorderPainted(false);
        btnPanel3.setContentAreaFilled(false);
        btnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel3ActionPerformed(evt);
            }
        });

        btnPanel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPanel4.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/salida.png"))); // NOI18N
        btnPanel4.setText("Salir");
        btnPanel4.setBorderPainted(false);
        btnPanel4.setContentAreaFilled(false);
        btnPanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBackLayout = new javax.swing.GroupLayout(jpBack);
        jpBack.setLayout(jpBackLayout);
        jpBackLayout.setHorizontalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackLayout.createSequentialGroup()
                .addGap(832, 832, 832)
                .addComponent(btnPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(btnPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jpBackLayout.setVerticalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1120, 70));

        lblHeader.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblHeader.setText("Buscar eventos cerca de mi");

        jPFilters.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Filtrado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        lblFilterByName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFilterByName.setText("Nombre del evento:");

        txtFilterByName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblBeginDate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblBeginDate.setText("Fecha de inicio:");

        lblFinalDate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFinalDate.setText("Fecha final:");

        lblFilterByLocation.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFilterByLocation.setText("Ubicación del evento:");

        txtFilterByLocation.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnFilter.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/filtrar.png"))); // NOI18N
        btnFilter.setText("FILTRAR");
        btnFilter.setContentAreaFilled(false);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        boxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hotels", "attractions ", "restaurants", "geos" }));

        javax.swing.GroupLayout jPFiltersLayout = new javax.swing.GroupLayout(jPFilters);
        jPFilters.setLayout(jPFiltersLayout);
        jPFiltersLayout.setHorizontalGroup(
            jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFiltersLayout.createSequentialGroup()
                .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPFiltersLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFiltersLayout.createSequentialGroup()
                                .addGap(707, 707, 707)
                                .addComponent(btnFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPFiltersLayout.createSequentialGroup()
                                .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPFiltersLayout.createSequentialGroup()
                                        .addComponent(lblFilterByName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFilterByName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPFiltersLayout.createSequentialGroup()
                                        .addComponent(lblFilterByLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFilterByLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(boxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPFiltersLayout.createSequentialGroup()
                                        .addComponent(lblBeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdcStar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(lblFinalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdcFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPFiltersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        jPFiltersLayout.setVerticalGroup(
            jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFiltersLayout.createSequentialGroup()
                .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPFiltersLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdcFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPFiltersLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFilterByName)
                            .addComponent(txtFilterByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFilterByLocation)
                            .addComponent(txtFilterByLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBeginDate)
                                .addComponent(lblFinalDate)
                                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdcStar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );

        btnClearFilter.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnClearFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/escoba.png"))); // NOI18N
        btnClearFilter.setText("Limpiar mi búsqueda anterior");
        btnClearFilter.setContentAreaFilled(false);
        btnClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSearchLayout = new javax.swing.GroupLayout(jpSearch);
        jpSearch.setLayout(jpSearchLayout);
        jpSearchLayout.setHorizontalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollAvailable)
                    .addComponent(btnClearFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jpSearchLayout.setVerticalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(scrollAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tabPanels.addTab("Eventos Disponibles", jpSearch);

        lblHeaderReservations.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblHeaderReservations.setText("Reservar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mi reservación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        lblUserR.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblUserR.setText("Usuario:");

        txtUserR.setEditable(false);
        txtUserR.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        lblDateR.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDateR.setText("Fecha de mi reservación:");

        txtDateR.setEditable(false);
        txtDateR.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        lblQuantityR.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblQuantityR.setText("Cantidad de personas/entradas:");

        spQuantityR.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        spQuantityR.setModel(new javax.swing.SpinnerNumberModel(1, null, 10, 1));

        lblEventId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblEventId.setText("Evento:");

        txtEventId.setEditable(false);
        txtEventId.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        btnConfirmR.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnConfirmR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/aceptar.png"))); // NOI18N
        btnConfirmR.setText("Confirmar");
        btnConfirmR.setBorderPainted(false);
        btnConfirmR.setContentAreaFilled(false);
        btnConfirmR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfirmR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfirmR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmRActionPerformed(evt);
            }
        });

        btnDisconfirmR.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDisconfirmR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/cancelado.png"))); // NOI18N
        btnDisconfirmR.setText("Cancelar");
        btnDisconfirmR.setBorderPainted(false);
        btnDisconfirmR.setContentAreaFilled(false);
        btnDisconfirmR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDisconfirmR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDisconfirmR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconfirmRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDisconfirmR, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmR, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDateR)
                            .addComponent(lblUserR, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDateR, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(txtUserR))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblQuantityR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spQuantityR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblEventId)
                                .addGap(12, 12, 12)
                                .addComponent(txtEventId, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserR)
                    .addComponent(txtUserR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEventId)
                    .addComponent(txtEventId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateR)
                    .addComponent(txtDateR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantityR)
                    .addComponent(spQuantityR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmR)
                    .addComponent(btnDisconfirmR, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre Usuario", "Fecha", "Entradas", "Evento"
            }
        ));
        tblReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservationsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblReservations);

        lblHeaderReservations1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblHeaderReservations1.setText("Historial de reservaciones:");

        javax.swing.GroupLayout jpReservationsLayout = new javax.swing.GroupLayout(jpReservations);
        jpReservations.setLayout(jpReservationsLayout);
        jpReservationsLayout.setHorizontalGroup(
            jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservationsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHeaderReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHeaderReservations1)
                    .addComponent(jScrollPane2))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jpReservationsLayout.setVerticalGroup(
            jpReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservationsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblHeaderReservations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHeaderReservations1)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        tabPanels.addTab("Reservaciones", jpReservations);

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName.setText("Apellidos:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Contraseña:");

        lblNameUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameUser.setText("Nombre:");

        lblHeaderMyProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeaderMyProfile.setText("Editar Mi Perfil");
        lblHeaderMyProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeaderMyProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblId_number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId_number.setText("Cédula:");

        btnUpdateInfoUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateInfoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/actUsuario.png"))); // NOI18N
        btnUpdateInfoUser.setText("Actualizar");
        btnUpdateInfoUser.setBorderPainted(false);
        btnUpdateInfoUser.setContentAreaFilled(false);
        btnUpdateInfoUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateInfoUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInfoUserActionPerformed(evt);
            }
        });

        lblEmailUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailUser.setText("Correo:");

        lblBirthDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBirthDate.setText("Fecha de Nacimiento:");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone.setText("Número de Teléfono:");

        javax.swing.GroupLayout jpmyProfileLayout = new javax.swing.GroupLayout(jpmyProfile);
        jpmyProfile.setLayout(jpmyProfileLayout);
        jpmyProfileLayout.setHorizontalGroup(
            jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmyProfileLayout.createSequentialGroup()
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpmyProfileLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword)
                            .addComponent(lblEmailUser)
                            .addComponent(lblId_number)
                            .addComponent(lblLastName)
                            .addComponent(lblNameUser)
                            .addComponent(lblBirthDate)
                            .addComponent(lblPhone))
                        .addGap(32, 32, 32)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdNumberProfile)
                            .addComponent(txtNameProfile)
                            .addComponent(txtLastNameProfile)
                            .addComponent(txtEmailProfile)
                            .addComponent(txtPasswordProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtPhoneProfile)
                            .addComponent(jdcUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpmyProfileLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblHeaderMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpmyProfileLayout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(btnUpdateInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jpmyProfileLayout.setVerticalGroup(
            jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmyProfileLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHeaderMyProfile)
                .addGap(49, 49, 49)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpmyProfileLayout.createSequentialGroup()
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameUser)
                            .addComponent(txtNameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId_number)
                            .addComponent(txtIdNumberProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastNameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailUser)
                            .addComponent(txtEmailProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBirthDate))
                    .addComponent(jdcUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPasswordProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jpmyProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhoneProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnUpdateInfoUser)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        tabPanels.addTab("Mi Perfil", jpmyProfile);

        getContentPane().add(tabPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 1120, 790));

        jpMenu.setBackground(new java.awt.Color(0, 0, 204));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnPanel1.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/plano-alt.png"))); // NOI18N
        btnPanel1.setText("Buscar eventos");
        btnPanel1.setBorderPainted(false);
        btnPanel1.setContentAreaFilled(false);
        btnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel1ActionPerformed(evt);
            }
        });
        jpMenu.add(btnPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, 190, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/lago_oscuro_1270_x_720.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jpMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel1ActionPerformed
        tabPanels.setSelectedIndex(0);
    }//GEN-LAST:event_btnPanel1ActionPerformed

    private void btnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel3ActionPerformed
        tabPanels.setSelectedIndex(2);
    }//GEN-LAST:event_btnPanel3ActionPerformed

    private void btnUpdateInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInfoUserActionPerformed
        cu.updatedUser(txtIdNumberProfile, txtNameProfile, txtLastNameProfile, jdcUser, txtEmailProfile, txtPhoneProfile, txtPasswordProfile);
    }//GEN-LAST:event_btnUpdateInfoUserActionPerformed

    private void btnPanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel4ActionPerformed
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPanel4ActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        this.cta.searchEvents(txtFilterByName, txtFilterByLocation, scrollAvailable, boxCategory, this);
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFilterActionPerformed

    private void btnConfirmRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmRActionPerformed
        //Event handler for the "Confirm Reservation" button, prompting the user to confirm the reservation.
        Event selectedEvent = eventPanel.getSelectedEvent();
        Place selectedPlace = eventPanel.getSelectedPlace();
        int option = JOptionPane.showConfirmDialog(this, "¿Deseas reservar el evento '" + selectedEvent.getName() + "'?", "Confirmar Reserva", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Set event and venue details in the database
            setPlaceDetails(selectedPlace);
            int generatedPlaceId = placeDAO.getIDPlaces(selectedPlace.getName());
            selectedEvent.setPlace_id(generatedPlaceId);

            setEventDetails(selectedEvent);
            int generatedEventId = eventDAO.getIDEvents(selectedEvent.getName());

            Integer quantity = (Integer) spQuantityR.getValue();
            cr.addReservation(txtUserR, txtDateR, quantity, generatedEventId);
            loadReservation();
        } else {
        }
    }//GEN-LAST:event_btnConfirmRActionPerformed

    private void btnDisconfirmRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconfirmRActionPerformed
        tabPanels.setSelectedIndex(0);
    }//GEN-LAST:event_btnDisconfirmRActionPerformed

    private void tblReservationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservationsMouseClicked
        cr.selectedRow(tblReservations);
    }//GEN-LAST:event_tblReservationsMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCategory;
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton btnConfirmR;
    private javax.swing.JButton btnDisconfirmR;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnPanel1;
    private javax.swing.JButton btnPanel3;
    private javax.swing.JButton btnPanel4;
    private javax.swing.JButton btnUpdateInfoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPFilters;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdcFinish;
    private com.toedter.calendar.JDateChooser jdcStar;
    private com.toedter.calendar.JDateChooser jdcUser;
    private javax.swing.JPanel jpBack;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpReservations;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JPanel jpmyProfile;
    private javax.swing.JLabel lblBeginDate;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblDateR;
    private javax.swing.JLabel lblEmailUser;
    private javax.swing.JLabel lblEventId;
    private javax.swing.JLabel lblFilterByLocation;
    private javax.swing.JLabel lblFilterByName;
    private javax.swing.JLabel lblFinalDate;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeaderMyProfile;
    private javax.swing.JLabel lblHeaderReservations;
    private javax.swing.JLabel lblHeaderReservations1;
    private javax.swing.JLabel lblId_number;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblQuantityR;
    private javax.swing.JLabel lblUserR;
    private javax.swing.JScrollPane scrollAvailable;
    private javax.swing.JSpinner spQuantityR;
    private javax.swing.JTabbedPane tabPanels;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTextField txtDateR;
    private javax.swing.JTextField txtEmailProfile;
    private javax.swing.JTextField txtEventId;
    private javax.swing.JTextField txtFilterByLocation;
    private javax.swing.JTextField txtFilterByName;
    private javax.swing.JTextField txtIdNumberProfile;
    private javax.swing.JTextField txtLastNameProfile;
    private javax.swing.JTextField txtNameProfile;
    private javax.swing.JPasswordField txtPasswordProfile;
    private javax.swing.JTextField txtPhoneProfile;
    private javax.swing.JTextField txtUserR;
    // End of variables declaration//GEN-END:variables
}
